version: 0.2

env:
  variables:
    CI: "false"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd my-react-app
      - npm install
  build:
    commands:
      - cd my-react-app
      - npm test -- --coverage

artifacts:
  base-directory: my-react-app/build
  files:
    - '**/*'